version: '3'
services:
    #   redis:
    #     image: "redis:alpine"
    #     ports:
    #       - "6379:6379"
    elasticsearch:
        image: 'docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.1'
        ports:
            - '9200:9200'
    mongo:
        image: 'mongo'
        ports:
            - '27017:27017'
    # api:
    #   build: .
    #   ports:
    #    - "3000:3000"
    #   #volumes:
    #   #  - ".:/app/src"
    #   depends_on:
    #    - "mongo"
    #    - "elasticsearch"
    #    - "redis"
